---
RecipeFormatVersion: "2020-01-25"
ComponentName: "DockerCompose"
ComponentVersion: "1.29.1"
ComponentType: "aws.greengrass.generic"
ComponentDescription: "Docker Compose v1.29.1"
ComponentPublisher: "Docker"
ComponentDependencies:
  Docker:
    VersionRequirement: ^0.0.0
    DependencyType: HARD
Manifests:
  - Platform:
      os: "linux"
    Name: "Linux"
    Lifecycle:
      Install:
        RequiresPrivilege: true
        Skipif: "onpath docker-compose"
        script: "sudo curl -L \"https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/bin/docker-compose && sudo chmod +x /usr/bin/docker-compose"
